routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {
    Route::resource('users', 'UsersController')->except('show');
    Route::resource('department', 'DepartmentsController')->except('show');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    //
    protected $table = 'department';

    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'logo',
    ];

    public function users()
    {
        return $this->belongsToMany('App\User', 'department_users', 'department_id', 'user_id');
    }
}

app/Http/Controllers/DepartmentsController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class DepartmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $departments = Department::paginate(4);
        return view('department.index', ['departments' => $departments]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $users = User::all();
        return view('department.create', ['users' => $users]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'description' => 'required|string',
            'logo' => 'required|image',
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        $path = Storage::putFile('logo', $request->file('logo')) ?? '';
        $department = Department::create([$request->name, $request->description, 'logo' => $path]);

        if($request->users) {
            $department->users()->attach($request->users);
        }

        return response()->redirectToRoute('department.edit', $department->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        //
        $users = User::all();
        $activeUsers = $department->users()->pluck('id');
        return view('department.edit', ['department' => $department, 'users' => $users, 'activeUsers' => $activeUsers->toArray()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Department $department)
    {
        //
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'description' => 'required|string',
            'logo' => 'nullable|image',
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        if($request->file('logo')) {
            $path = Storage::putFile('logo', $request->file('logo'));
            $department->update([$request->name, $request->description, 'logo' => $path ?? '']);
        } else {
            $department->update([$request->name, $request->description]);
        }

        $department->users()->detach();
        if($request->users) {
            $department->users()->attach($request->users);
        }

        return back()
            ->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        //
        $department->delete();
        return response()->redirectToRoute('department.index');
    }
}

resources/views/department/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Departments') }}</div>

                    <div class="card-body">
                        <form action="{{ route('department.store') }}" method="POST" class="w-100" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="inputName">{{ __('Name') }}</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" id="inputName" placeholder="Enter name" name="name" value="{{ old('name') }}">
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="inputDescription">{{ __('Description') }}</label>
                                <textarea type="text" class="form-control @error('description') is-invalid @enderror" id="inputDescription" placeholder="Enter description" name="description">{{ old('description') }}</textarea>
                                @error('description')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="inputLogo">{{ __('Logo') }}</label>
                                <input type="file" class="form-control @error('logo') is-invalid @enderror" id="inputLogo" placeholder="Enter logo" accept="image/*" name="logo" value="{{ old('logo') }}">
                                @error('logo')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            @foreach($users as $user)
                                <div class="form-group" style="margin-bottom: 0">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="checkbox" id="inlineCheckbox{{ $user->id }}" name="users[]">
                                        <label class="form-check-label" for="inlineCheckbox{{ $user->id }}">{{ $user->name }}</label>
                                    </div>
                                </div>
                            @endforeach

                            <button type="submit" class="btn btn-primary">Send</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/department/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Departments') }}</div>

                    <div class="card-body">
                        <form action="{{ route('department.update', $department->id) }}" method="POST" class="w-100" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                                <label for="inputName">{{ __('Name') }}</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" id="inputName" placeholder="Enter name" name="name" value="{{ $department->name }}">
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="inputDescription">{{ __('Description') }}</label>
                                <textarea class="form-control @error('description') is-invalid @enderror" id="inputDescription" placeholder="Enter description" name="description">{{ $department->description }}</textarea>
                                @error('description')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <img src="{{ asset($department->logo) }}">
                                <label for="inputLogo">{{ __('Logo') }}</label>
                                <input type="file" class="form-control @error('logo') is-invalid @enderror" id="inputLogo" placeholder="Enter logo" accept="image/*" name="logo" value="{{ $department->logo }}">
                                @error('logo')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            @foreach($users as $user)
                                <div class="form-group" style="margin-bottom: 0">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="checkbox" id="inlineCheckbox{{ $user->id }}" name="users[]" value="{{ $user->id }}" {{ in_array($user->id, $activeUsers) ? 'checked' : '' }}>
                                        <label class="form-check-label" for="inlineCheckbox{{ $user->id }}">{{ $user->name }}</label>
                                    </div>
                                </div>
                            @endforeach

                            <button type="submit" class="btn btn-primary">Send</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/department/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Departments') }}  <a href="{{ route('department.create') }}" class="btn btn-secondary btn-sm float-right">{{ __('Add') }}</a></div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">{{ __('Logo') }}</th>
                                <th scope="col">{{ __('Text') }}</th>
                                <th scope="col">{{ __('Users') }}</th>
                                <th scope="col">{{ __('Action') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($departments as $department)
                                <tr>
                                    <td><img src="{{ asset($department->logo) }}" style="max-width: 100px; height: auto"></td>
                                    <td>
                                        {{ $department->name }}<br>
                                        {{ $department->description }}
                                    </td>
                                    <td>
                                        <ul>
                                            @foreach($department->users()->pluck('name') as $name)
                                                <li>{{ $name }}</li>
                                            @endforeach
                                        </ul>
                                    </td>
                                    <td>
                                        <a href="{{ route('department.edit', $department->id) }}" class="btn btn-secondary btn-sm">{{ __('Edit') }}</a>
                                        <button type="submit" form="formDestroy" class="btn btn-danger btn-sm">{{ __('Delete') }}</button>
                                        <form action="{{ route('department.destroy', $department->id) }}" method="POST" id="formDestroy">
                                            @method('DELETE')
                                            @csrf
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        {{ $departments->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection